<?php

/**
 * BaseTianPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $content
 * @property string $release_date
 * @property integer $position
 * 
 * @method string   getType()         Returns the current record's "type" value
 * @method string   getContent()      Returns the current record's "content" value
 * @method string   getReleaseDate()  Returns the current record's "release_date" value
 * @method integer  getPosition()     Returns the current record's "position" value
 * @method TianPost setType()         Sets the current record's "type" value
 * @method TianPost setContent()      Sets the current record's "content" value
 * @method TianPost setReleaseDate()  Sets the current record's "release_date" value
 * @method TianPost setPosition()     Sets the current record's "position" value
 * 
 * @package    china_blog_test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTianPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tian_post');
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('release_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}