<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/21 14:17:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tiantian',
  'username' => 'test',
  'password' => 'test',
  'name' => 'doctrine',
)),);
